name: Windows

env:
  CONAN_REPOSITORY: https://conan.rgpaul.com
  CONAN_REPOSITORY_NAME: rgpaul
  CONAN_PACKAGE_NAME: godot-cpp
  CONAN_USER: rgpaul
  CONAN_CHANNEL: stable

on: 
  push:
    branches:
      - master

jobs:

  x86_64-Release:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
      shell: bash
    - name: checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86_64 -BUILD_TYPE Release
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  x86_64-Debug:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
      shell: bash
    - name: checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86_64 -BUILD_TYPE Debug
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  x86-Release:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
      shell: bash
    - name: checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86 -BUILD_TYPE Release
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell

  x86-Debug:
    runs-on: windows-2019
    env:
      GITHUB_OS_NAME: windows
      CONAN_PWD: ${{ secrets.CONAN_PWD }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: fetch all tags and all history for all tags and branches
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        git fetch --prune --unshallow
      shell: bash
    - name: checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive
    - name: get version from tags
      run: echo ::set-env name=LIBRARY_VERSION::$(git describe --abbrev=0 --tags)
      shell: bash
    - name: install and setup conan
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-setup.ps1
      shell: powershell
    - name: create conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\build-windows.ps1 -ARCH x86 -BUILD_TYPE Debug
      shell: powershell
    - name: deploy conan packages
      run: powershell -File ${env:GITHUB_WORKSPACE}\.github\scripts\conan-deploy.ps1
      shell: powershell
